### ISSUE TITLE
Better README?

### ISSUE THREAD

**Issue by Alex-Keyes** [boonebgorges/bp-archive-groups#1]
Hi Boone,

Could you please write a better readme for how to use this PHP?  How are the archives stored?  Could I have more information about the best use of this plugin?

**Comment by boonebgorges** [comment]
Hey @Alex-Keyes - This plugin is incomplete and doesn't have a UI. it's intended to be part of a more complete solution for allowing users or admins to mark groups as "archived", and then to hide those groups from group lists except when the URL is `?bpag_status=archived`. The groups continue to exist in the BP installation as normal use; they're just flagged as "archived" with a piece of group metadata.

If you can give me more info about what you're aiming to do - either here or in a private channel if it's more appropriate - I can let you know whether this plugin is a useful starting point.

**Comment by Alex-Keyes** [comment]
Let me send you and email and we can talk more about the feature I want to develop.
